package eu.w4.contrib.bpmnplus.service.notifier.rest;

public enum NotificationType
{
  PROCESS_INSTANCE_READY,
  PROCESS_INSTANCE_ACTIVE,
  PROCESS_INSTANCE_ASSIGNED,
  PROCESS_INSTANCE_SAVED,
  PROCESS_INSTANCE_COMPLETED,
  PROCESS_INSTANCE_TERMINATED,
  PROCESS_INSTANCE_FAILED,
  ACTIVITY_INSTANCE_READY,
  ACTIVITY_INSTANCE_ACTIVE,
  ACTIVITY_INSTANCE_ASSIGNED,
  ACTIVITY_INSTANCE_CLAIMED,
  ACTIVITY_INSTANCE_DISCLAIMED,
  ACTIVITY_INSTANCE_COMPLETED,
  ACTIVITY_INSTANCE_TERMINATED,
  ACTIVITY_INSTANCE_FAILED,
  EVENT_INSTANCE_ACTIVE,
  EVENT_INSTANCE_COMPLETED,
  EVENT_INSTANCE_TERMINATED,
  EVENT_INSTANCE_WITHDRAWN;
}
